apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsmagicproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsmagicproxy
  template:
    metadata:
      labels:
        app: tsmagicproxy
    spec:
      containers:
      - name: tsmagicproxy
        image: tsmagicproxy
        ports:
        - containerPort: 53
          protocol: UDP
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: ts-magicproxy-auth
              key: TS_AUTHKEY
        - name: TSNET_FORCE_LOGIN
          value: "1"
        volumeMounts:
        - name: tailscale-state
          mountPath: /var/lib/tsmagicproxy
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: tailscale-state
        emptyDir: {} 